### ISSUE TITLE
incorrect authentication

### ISSUE THREAD

**Issue by melissabell456** [nss-day-cohort-23/group-project-pinterest-clearly-vague#2]
## Expected Behavior
- user can authenticate with their google accounts

## Actual Behavior
- user authentication functions are set up as email/password 

## Steps to Reproduce Behavior 
- n/a

## Module Suspected / Relevant Files 
- authfactory

## Related Issues 
-

**Comment by iiimosley** [comment]
Closing issue because users can now be authenticated & log in/out via Google (Resolved)
